version: '3.0'

services:

  db:
    image: mysql
    container_name: db
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    stdin_open: true
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: task_logger
    ports:
      - 3306:3306

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080